name: layout_base
description: Base Flutter com layout visual neutro.
publish_to: none
# Versao visivel + numero interno usados tambem pelo Android.
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - imagens/logo.png
