# Propriedades do Gradle Android.
# Observacao: ajustes de memoria/build usados pelo Flutter ao gerar APK.
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# OBS: permite compilar no Windows mesmo com "Expedição" no caminho da pasta.
android.overridePathCheck=true
